config/routes.rb
Rails.application.routes.draw do
  localized do
    devise_for :users, controllers: {
      registrations: 'user/registrations',
      sessions: 'user/sessions'
    }
    
    # AREA DE ADMINS
    resources :videos
    resources :posts
    get '/users', to: 'users#index', as: :users

    # AREA DE USUARIOS COMUNS
    get '/profile/:user_id', to: 'pages#profile', as: :profile
    get '/home', to: 'pages#home', as: :home
    match '/all_videos', to: 'pages#videos', as: :all_videos, via: [:get, :post]
    match '/all_posts', to: 'pages#posts', as: :all_posts, via: [:get, :post]

    # AÇÕES ENTRE ADMIN/USUARIOS COM OUTROS USUARIOS
    resources :relationships, only: :index
    post '/:relationship_id/accept', to: 'relationships#accept', as: :accept_relationship
    post '/:relationship_id/reject', to: 'relationships#reject', as: :reject_relationship
    post '/add_friend', to: 'relationships#create', as: :create_relationship
    post '/remove_friend', to: 'relationships#destroy', as: :destroy_relationship
    post '/ban', to: 'users#ban', as: :ban_user
    post '/became_admin', to: 'users#became_admin', as: :became_admin

    # ALTERAR AVATAR
    post '/change_photo', to: 'users#change_photo', as: :change_photo

    # PUBLICAÇÕES E AVALIAÇÕES
    post '/rate', to: 'rater#create', as: 'rate'
    resources :comments, except: [:edit, :update, :show]

    # ALTERAR IDIOMA
    get 'set_language/portuguese'
    get 'set_language/spanish'

    root "pages#home"
  end
end

app/models/relationship.rb
# I'm pretty sure I'm a top-level class documentation comment
class Relationship < ActiveRecord::Base
  has_enumeration_for :situation,
  with: RelationshipSituation, create_helpers: { prefix: true }

  scope :by_situation, -> (param) { where(situation: param) }

  def adder_user
    User.find(adder_id)
  end

  def added_user
    User.find(added_id)
  end

  def displaying_for(user)
    user == adder_user ? added_user : adder_user
  end
end

app/controllers/relationships_controller.rb
# I'm pretty sure I'm a top-level class documentation comment
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @relationships = Relationship.where(
      'adder_id = :id OR added_id = :id', id: current_user.id
    )
  end

  def create
    @user = User.find(params[:relationship][:user_id])
    Relationship.create(adder_id: current_user.id, added_id: @user.id)
    @relationship = @user.relationship?(current_user).first
  end

  def accept
    @user = current_user
    @relationship = Relationship.find(params[:relationship_id])
    @relationship.update(situation: 'accepted')
    @relationships = Relationship.where(
      'adder_id = :id OR added_id = :id', id: current_user.id
    )
  end

  def reject
    @user = current_user
    @relationship = Relationship.find(params[:relationship_id])
    @relationship.destroy
    @relationships = Relationship.where(
      'adder_id = :id OR added_id = :id', id: current_user.id
    )
  end

  def destroy
    @user = User.find(params[:user_id])
    Relationship.where(
      adder_id: [current_user.id, @user.id],
      added_id: [@user.id, current_user.id]
    ).destroy_all
    @relationship = @user.relationship?(current_user).first
  end
end

app/views/relationships/_form.html.erb
<div class="relationship-situation">
  <% unless @relationship %>
    <div class="center">
      <%= simple_form_for :relationship, url: create_relationship_path, method: :post, remote: true do |f| %>
        <%= f.input :user_id, as: :hidden, input_html: { value: @user.id } %>
        <%= f.submit t('user_card.relationship.add_friend'),
        class: 'w-button add-friend',
        data: { disable_with: t('default.sending') },
        style: 'margin-top: 10px;' %>
      <% end %>
      <!-- <a href="#" class="w-button ban-user"><%= t('user_card.relationship.ban') %></a><a href="#" class="w-button became-admin"><%= t('user_card.relationship.became_admin') %></a> -->
    </div>
  <% else %>
    <% if !@relationship.situation_pending? %>
      <b><%= link_to t('user_card.relationship.unfriend'), destroy_relationship_path(user_id: @user.id), method: :post, remote: true,
          class: 'unfriend-link', data: { disable_with: 'Cancelando...' }%></b>
    <% elsif @relationship.adder_user == current_user %>
      <div class="center">
        <%= link_to t('default.waiting_acceptation'), "#", class: 'w-button add-friend' %>
        <%= link_to t('default.cancel_request'), destroy_relationship_path(user_id: @user.id), method: :post, remote: true,
            data: { disable_with: t('default.canceling') }%>
      </div>
    <% elsif @relationship.added_user == current_user %>
      <div class="center">
        <%= link_to t('default.accept'), accept_relationship_path(@relationship), method: :post, remote: true, class: 'w-button btn-success add-friend' %>
        <%= link_to t('default.reject'), reject_relationship_path(@relationship), method: :post, remote: true,
            data: { disable_with: t('default.canceling') }%>
      </div>
    <% end %>
  <% end %>
</div>

app/views/relationships/_friends.html.erb
<% if @relationships.any? %>
  <% @relationships.each_slice(4).each do |relationships| %>
    <div class="w-row">
      <% relationships.each do |relationship| %>
        <% user = relationship.displaying_for(current_user) %>
        <div class="w-col w-col-3">
          <div class="user-li friends-list">
            <div class="avatar-circle sm" style="background-image: url(<%= user.avatar.url || 'assets/12247144_985681451493689_3460159843447436262_n.jpg' %>)">
              <% if relationship.situation_pending? && relationship.adder_user != current_user %>
                <%= link_to '', destroy_relationship_path(relationship.id), method: :post, remote: true, class: 'w-inline-block friendship-option left'  %>
                <%= link_to '', accept_relationship_path(relationship), method: :post, remote: true, class: 'w-inline-block friendship-option right'  %>
              <% end %>
            </div>
            <b><%= link_to user.name, profile_path(user), class: 'user-name frienshiplist' %></b>
            <div class="relationship-sit"><%= t('default.waiting_acceptation') if relationship.situation_pending?  %></div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% else %>
  <div class="alert alert-info"><strong><%= current_user.name %>: </strong><%= t('relationship.empty') %></div>
<% end %>

app/views/relationships/accept.js.erb
$('.relationships').replaceWith('<%=j render "relationships/friends" %>');

app/views/relationships/create.js.erb
$(".relationship-situation").replaceWith('<%=j render "relationships/form" %>');

app/views/relationships/destroy.js.erb
$(".relationship-situation").replaceWith('<%=j render "relationships/form" %>');
$(".user-counters").replaceWith('<%=j render "shared/user_counters" %>');

app/views/relationships/index.html.erb
<h1 class="highlight-title"><%= t('title.my_friends') %></h1>

<div class="relationships">
  <%= render 'relationships/friends' %>
</div>

app/views/relationships/reject.js.erb
$('.relationships').replaceWith('<%=j render "relationships/friends" %>');