config/routes.rb
Rails.application.routes.draw do
  localized do
    devise_for :users, controllers: {
      registrations: 'user/registrations',
      sessions: 'user/sessions'
    }
    
    # AREA DE ADMINS
    resources :videos
    resources :posts
    get '/users', to: 'users#index', as: :users

    # AREA DE USUARIOS COMUNS
    get '/profile/:user_id', to: 'pages#profile', as: :profile
    get '/home', to: 'pages#home', as: :home
    match '/all_videos', to: 'pages#videos', as: :all_videos, via: [:get, :post]
    match '/all_posts', to: 'pages#posts', as: :all_posts, via: [:get, :post]

    # AÇÕES ENTRE ADMIN/USUARIOS COM OUTROS USUARIOS
    resources :relationships, only: :index
    post '/:relationship_id/accept', to: 'relationships#accept', as: :accept_relationship
    post '/:relationship_id/reject', to: 'relationships#reject', as: :reject_relationship
    post '/add_friend', to: 'relationships#create', as: :create_relationship
    post '/remove_friend', to: 'relationships#destroy', as: :destroy_relationship
    post '/ban', to: 'users#ban', as: :ban_user
    post '/became_admin', to: 'users#became_admin', as: :became_admin

    # ALTERAR AVATAR
    post '/change_photo', to: 'users#change_photo', as: :change_photo

    # PUBLICAÇÕES E AVALIAÇÕES
    post '/rate', to: 'rater#create', as: 'rate'
    resources :comments, except: [:edit, :update, :show]

    # ALTERAR IDIOMA
    get 'set_language/portuguese'
    get 'set_language/spanish'

    root "pages#home"
  end
end

app/models/video.rb
# I'm pretty sure I'm a top-level class documentation comment
class Video < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  ratyrate_rateable 'like'

  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  validates :url, :title_pt, :title_es, :tags_pt, :tags_es, presence: true
  validates :url, format: {
    with: /^(?:https?:\/\/)?(?:www.)?youtu(?:\.be|be\.com)\/(?:watch\?v=)?([\w-]{10,})/,
    multiline: true
  }

  def title
    I18n.locale == :'pt-BR' ? 'title_pt' : 'title_es'
  end

  def parse_url
    regex = /(?:.be\/|\/watch\?v=|\/(?=p\/))([\w\/\-]+)/
    url.match(regex)[1]
  end

  def tag_list(locale)
    send('tags_' + locale).delete(';').split(',').reject(&:blank?)
  end

  def self.search(params)
    videos = Video.order(created_at: :desc)
    videos = videos.where('lower(title_pt) LIKE :term || lower(tags_pt) LIKE :term',
            term: "%#{params[:term].downcase}%") if params[:term].present?
    videos
  end
end

app/controllers/videos_controller.rb
# I'm pretty sure I'm a top-level class documentation comment
class VideosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_video, except: [:new, :create, :index]

  def index
    @user = current_user
    @videos = current_user.videos.search(params).page(params[:page]).per(9).order(created_at: :desc)
    authorize Video.new
  end

  def new
    @video = current_user.videos.new
    authorize @video
  end

  def create
    @video = current_user.videos.create(video_params)
    authorize @video
    respond_with @video, location: -> { videos_url }
  end

  def show
    @comment = current_user.comments.new
    @comments = @video.comments.by_locale(I18n.locale).order(created_at: :desc)
  end

  def edit
    authorize @video
  end

  def update
    authorize @video
    @video.update(video_params)
    respond_with @video, location: -> { videos_url }
  end

  def destroy
    authorize @video
    @video.destroy
    respond_with @video, location: -> { videos_url }
  end

  private

  def video_params
    params.require(:video).permit(
      :url, :title_pt, :title_es, :tags_pt, :tags_es
    )
  end

  def set_user
    @user = current_user
  end

  def set_video
    @video = Video.friendly.find(params[:id])
  end
end

app/views/videos/_form.html.erb
<div class="w-form">
  <%= simple_form_for @video do |f| %>

    <%= render 'layouts/error_box', resource: @video %>

    <%= f.input :title_pt, placeholder: t('helper.placeholder.title_pt'), input_html: { class: 'w-input input-rounded' } %>
    <%= f.input :title_es, placeholder: t('helper.placeholder.title_es'), input_html: { class: 'w-input input-rounded' } %>
    <%= f.input :url, placeholder: t('helper.placeholder.video_url'), input_html: { class: 'w-input input-rounded' } %>

    <hr>
    <%= f.input :tags_pt, input_html: { class: 'w-input input-rounded tags' } %>
    <hr>
    <%= f.input :tags_es, input_html: { class: 'w-input input-rounded tags' } %>

    <div class="pull-right" style="margin-top: 20px;">
      <%= f.button :submit, class: 'w-button', data: { disable_with: 'Salvando...' } %>
    </div>
  <% end %>
</div>


<%= content_for :bottom_js do %>
  <script type="text/javascript">
    $('.tags').tagsInput({
      'height':'100px',
      'width':'100%',
      'interactive':true,
      'defaultText':'',
      'delimiter': [',',';'],   // Or a string with a single delimiter. Ex: ';'
      'removeWithBackspace' : true,
      'minChars' : 3,
      'placeholderColor' : '#666666'
    });
  </script>
<% end %>

app/views/videos/_video.html.erb
<b><%= link_to video.send("title_#{current_locale}"), video_path(video), class: 'post-title' %></b>
<div class="post-date"><%= link_to video.user.name, profile_path(video.user) %>- <%= video.created_at.strftime("%d/%m/%Y - %H:%M") %></div>

app/views/videos/_videos_list.html.erb
<div class="videos-list">
  <% @videos.each_slice(3) do |videos| %>
    <div class="w-row">
      <% videos.each do |video| %>
        <div class="w-col w-col-4 w-col-small-4">
          <div class="user-li">
            <div class="video-square" style="background-image: url('http://img.youtube.com/vi/<%= video.parse_url %>/0.jpg')"></div>
            <b><%= link_to video.send("title_#{current_locale}"), edit_video_path(video), class: 'user-name' %></b>
            <div class="center">
              <%= link_to t('default.delete'), video_path(video),
                  method: :delete, class: 'w-button btn-danger btn-sm',
                  style: 'width: 100px;',
                  data: { disable_with: t('default.delete') }%>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/videos/edit.html.erb
<div class="pull-right" style="margin-bottom: 20px;">
  <%= link_to t('back'), :back %>
</div>
<%= render 'form' %>

app/views/videos/index.html.erb
<div class="pull-right" style="margin-bottom: 20px;">
  <%= link_to t('video.new'), new_video_path, class: 'w-button' %>
</div>

<%= render 'shared/search_form', url: videos_path, placeholder: t('helper.placeholder.tags') %>
<hr>
<% if @videos.any? %>
  <%= render 'videos_list' %>
  <%= paginate @videos %>
<% else %>
  <div class="alert alert-info">
    <strong>Videos: </strong><%= t('video.empty') %></div>
<% end %>

app/views/videos/new.html.erb
<div class="pull-right" style="margin-bottom: 20px;">
  <%= link_to t('back'), :back %>
</div>
<%= render 'form' %>

app/views/videos/show.html.erb
<div class="w-form">
  <h1 class="post-title pull-right"><%= @video.send("title_#{current_locale}") %></h1>
  <div class="post-date pull-right"><%= link_to @video.user.name, profile_path(@video.user) %>- <%= @video.created_at.strftime("%d/%m/%Y - %H:%M") %></div>
  <div style="padding-top: 56.17021276595745%;" class="w-embed w-video">
    <iframe class="embedly-embed" src="http://www.youtube.com/embed/<%= @video.parse_url %>?autoplay=1" scrolling="no" frameborder="0" allowfullscreen=""></iframe>
  </div>

  <%= tag_list_from @video %>

  <div class="rating-box">
    <div><%= t('default.rate_this_post') %></div>
    <%= rating_for @video, "like", star: 5, star_path: '/images', enable_half: true, disable_after_rate: true, cancel: true %>
  </div>

  <%= render 'comments/form' %>
</div>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
  <% end %>
</div>