config/routes.rb
Rails.application.routes.draw do
  localized do
    devise_for :users, controllers: {
      registrations: 'user/registrations',
      sessions: 'user/sessions'
    }
    
    # AREA DE ADMINS
    resources :videos
    resources :posts
    get '/users', to: 'users#index', as: :users

    # AREA DE USUARIOS COMUNS
    get '/profile/:user_id', to: 'pages#profile', as: :profile
    get '/home', to: 'pages#home', as: :home
    match '/all_videos', to: 'pages#videos', as: :all_videos, via: [:get, :post]
    match '/all_posts', to: 'pages#posts', as: :all_posts, via: [:get, :post]

    # AÇÕES ENTRE ADMIN/USUARIOS COM OUTROS USUARIOS
    resources :relationships, only: :index
    post '/:relationship_id/accept', to: 'relationships#accept', as: :accept_relationship
    post '/:relationship_id/reject', to: 'relationships#reject', as: :reject_relationship
    post '/add_friend', to: 'relationships#create', as: :create_relationship
    post '/remove_friend', to: 'relationships#destroy', as: :destroy_relationship
    post '/ban', to: 'users#ban', as: :ban_user
    post '/became_admin', to: 'users#became_admin', as: :became_admin

    # ALTERAR AVATAR
    post '/change_photo', to: 'users#change_photo', as: :change_photo

    # PUBLICAÇÕES E AVALIAÇÕES
    post '/rate', to: 'rater#create', as: 'rate'
    resources :comments, except: [:edit, :update, :show]

    # ALTERAR IDIOMA
    get 'set_language/portuguese'
    get 'set_language/spanish'

    root "pages#home"
  end
end

app/views/shared/_flash.html.erb
<div class="flash-message">
  <% for key, msg in flash %>
    <% flash_class = key.to_s == "notice" ? "success" : "fail" %>
    <div class="alert alert-<%= flash_class %>">
      <div style="text-align: center;"><%= msg %></div>
    </div>
  <% end %>
</div>


<!-- <div class="alert alert-success"><strong data-new-link="true">Well done!</strong>&nbsp;You successfully read this important alert message.</div>
<div class="alert alert-info"><strong data-new-link="true">Well done!</strong>&nbsp;You successfully read this important alert message.</div>
<div class="alert alert-warning"><strong data-new-link="true">Well done!</strong>&nbsp;You successfully read this important alert message.</div>
<div class="alert alert-fail"><strong data-new-link="true">Well done!</strong>&nbsp;You successfully read this important alert message.</div> -->

app/views/shared/_language_options.html.erb
<div class="pull-right">
  <%= link_to "", set_language_portuguese_path, class: "w-inline-block language-flag br #{ 'active' if I18n.locale == 'pt-BR'.to_sym }" %>
  <%= link_to "", set_language_spanish_path, class: "w-inline-block language-flag es #{ 'active' if I18n.locale == :es }" %>
</div>

app/views/shared/_search_form.html.erb
<%= form_tag url, method: :get do %>
<%= text_field_tag :term, params[:term], placeholder: placeholder, class: "w-input" %>

  <div class="pull-right">
    <%= submit_tag t('default.search'), class: 'w-button btn-success' %>
  </div>
<% end %>

app/views/shared/_user_avatar.html.erb
<div class="user-avatar">
  <div class="avatar-box">
    <%= form_tag change_photo_path, method: :post, remote: true, multipart: true, id: 'change_photo_form' do %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= file_field_tag :avatar, accept: 'image/png ,image/jpeg, image/jpg', style: 'display: none;', id: 'uploadAvatar' %>
    <% end %>

    <div class="avatar-circle no-bg" style="background-image: url(<%= @user.avatar.url || '/images/12247144_985681451493689_3460159843447436262_n.jpg' %>)"></div>

    <%= display_admin_cert(@user) %>
  </div>
  <b><%=  link_to t('user_card.change_avatar'), "#", id: "changeAvatar", class: 'change-avatar' if @user == current_user %></b>
</div>

app/views/shared/_user_card.html.erb
<div class="profile-side">
  <%= render 'shared/user_avatar' %>
</div>

<b><%= link_to @user.name, profile_path(@user) %></b>

<%= admin? @user %>

<div><%= t('user_card.since_by') %>: <%= @user.created_at.strftime("%d/%m/%Y - %H:%M") %></div>

<%= render 'shared/user_counters' %>

<%= render 'relationships/form' if @user != current_user %>

<% if current_user.is_admin %>
  <ul class="w-list-unstyled">
    <li class="side-menu-link users">
      <%= link_to users_path, class: 'w-inline-block menu-list' do %>
        <div class="side-menu-text"><strong><%= t('user_card.users') %></strong></div>
      <% end %>
    </li>
    <li class="side-menu-link">
      <%= link_to videos_path, class: 'w-inline-block menu-list' do %>
        <div class="side-menu-text"><strong><%= t('user_card.videos') %></strong>
        </div>
      <% end %>
    </li>
    <li class="side-menu-link news">
      <%= link_to posts_path, class: 'w-inline-block menu-list' do %>
        <div class="side-menu-text"><strong><%= t('user_card.posts') %></strong>
        </div>
      <% end %>
    </li>
  </ul>
<% end %>

<%= content_for :bottom_js do %>
  <script type="text/javascript">
    $("#changeAvatar").click(function(){
      $("#uploadAvatar").click();
    });

    $("#uploadAvatar").change(function(){
      $("#change_photo_form").submit();
    });
  </script>
<% end %>

app/views/shared/_user_counters.html.erb
<div class="user-counters">
  <ul class="w-list-unstyled count-ul">
    <li class="count-list">
      <h3 class="num-counter"><%= @user.friends.count %></h3>
      <div><%= t('user_card.friends') %></div>
    </li>
    <li class="count-list">
      <h3 class="num-counter"><%= @user.videos.count %></h3>
      <div><%= t('user_card.videos') %></div>
    </li>
    <li class="count-list">
      <h3 class="num-counter"><%= @user.posts.count %></h3>
      <div><%= t('user_card.posts') %></div>
    </li>
  </ul>
</div>