config/routes.rb
Rails.application.routes.draw do
  localized do
    devise_for :users, controllers: {
      registrations: 'user/registrations',
      sessions: 'user/sessions'
    }
    
    # AREA DE ADMINS
    resources :videos
    resources :posts
    get '/users', to: 'users#index', as: :users

    # AREA DE USUARIOS COMUNS
    get '/profile/:user_id', to: 'pages#profile', as: :profile
    get '/home', to: 'pages#home', as: :home
    match '/all_videos', to: 'pages#videos', as: :all_videos, via: [:get, :post]
    match '/all_posts', to: 'pages#posts', as: :all_posts, via: [:get, :post]

    # AÇÕES ENTRE ADMIN/USUARIOS COM OUTROS USUARIOS
    resources :relationships, only: :index
    post '/:relationship_id/accept', to: 'relationships#accept', as: :accept_relationship
    post '/:relationship_id/reject', to: 'relationships#reject', as: :reject_relationship
    post '/add_friend', to: 'relationships#create', as: :create_relationship
    post '/remove_friend', to: 'relationships#destroy', as: :destroy_relationship
    post '/ban', to: 'users#ban', as: :ban_user
    post '/became_admin', to: 'users#became_admin', as: :became_admin

    # ALTERAR AVATAR
    post '/change_photo', to: 'users#change_photo', as: :change_photo

    # PUBLICAÇÕES E AVALIAÇÕES
    post '/rate', to: 'rater#create', as: 'rate'
    resources :comments, except: [:edit, :update, :show]

    # ALTERAR IDIOMA
    get 'set_language/portuguese'
    get 'set_language/spanish'

    root "pages#home"
  end
end

app/models/user.rb
# I'm pretty sure I'm a top-level class documentation comment
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  extend FriendlyId
  friendly_id :name, use: :slugged

  ratyrate_rater

  has_enumeration_for :status,
  with: UserStatus, create_helpers: { prefix: true }

  has_many :videos, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :nullify

  def friends
    Relationship.where(
      'adder_id = :id OR added_id = :id', id: id
    ).by_situation('accepted')
  end

  def relationship?(user)
    Relationship.where(
      'adder_id = :user_id AND added_id = :id OR
      adder_id = :id AND added_id = :user_id',
      id: id, user_id: user.id
    )
  end

  def active_for_authentication?
    super && self.status_active?
  end

  def self.search(params)
    users = User.order(created_at: :desc)
    users = users.where('lower(name) LIKE :term || lower(email) LIKE :term',
            term: "%#{params[:term].downcase}%") if params[:term].present?
    users
  end
end

app/controllers/user/registrations_controller.rb
class User
  class RegistrationsController < Devise::RegistrationsController
  end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
# I'm pretty sure I'm a top-level class documentation comment
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorized?, except: :change_photo

  def index
    @user = current_user
    @users = User.search(params).page(params[:page]).per(9).
             where.not(id: current_user.id)
  end

  def ban
    @user = User.find(params[:user_id])
    @user.status_banned? ? @user.status_active! : @user.status_banned!
    @user.save
    @users = User.all.reject { |u| u == current_user }
  end

  def became_admin
    @user = User.find(params[:user_id])
    @user.is_admin = @user.is_admin ? false : true
    @user.save
    @users = User.all.reject { |u| u == current_user }
  end

  def change_photo
    @user = current_user
    @user.update(avatar: params[:avatar])
    redirect_to :back
  end

  private

  def authorized?
    if !current_user.is_admin
      flash[:alert] = t("You are not authorized to perform this action")
      redirect_to(request.referrer || root_path)
    end
  end
end

app/helpers/user_helper.rb
# I'm pretty sure I'm a top-level class documentation comment
module UserHelper
  def admin?(user)
    '<div><strong>ADMIN</strong></div>'.html_safe if user.is_admin
  end

  def display_admin_cert(user)
    '<div class="admin-cert"></div>'.html_safe if user.is_admin
  end
end

app/views/user/shared/_forms.html.erb
<h1 class="page-header"><%= t('title.sign_in_or_register') %></h1>
<div class="w-row">
  <div class="w-col w-col-5">
    <div class="w-form">
      <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <%= f.input :email, placeholder: t('helper.placeholder.email'), input_html: { class: 'w-input input-rounded' } %>
        <%= f.input :password, placeholder: t('helper.placeholder.new_password'), input_html: { class: 'w-input input-rounded' } %>

        <div class="pull-right">
          <%= f.submit t('default.enter'), class: 'w-button', data: { disable_with: t('default.wait') } %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="w-col w-col-1"></div>

  <div class="w-col w-col-6">
    <div class="w-form">
      <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>

        <%= render 'layouts/error_box', resource: resource %>

        <%= f.input :name, placeholder: t('helper.placeholder.name'), input_html: { class: 'w-input input-rounded' } %>
        <%= f.input :email, placeholder: t('helper.placeholder.email'), input_html: { class: 'w-input input-rounded' } %>
        <%= f.input :password, placeholder: t('helper.placeholder.password'), input_html: { class: 'w-input input-rounded' } %>
        <%= f.input :password_confirmation, placeholder: t('helper.placeholder.password_confirmation'), input_html: { class: 'w-input input-rounded' } %>

        <div class="pull-right">
          <%= f.button :submit, class: 'w-button', data: { disable_with: t('default.wait') } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>